name: SubsystemBauwelt
version: ${project.version}
main: me.maximilian1021.main.Main
api-version: 1.16
authors: [ Maximilian1021 ]
description: Regelt Funktionen auf dem Bauwelt Server
website: max1021.de
